import type { RuntimeSnapshot } from '../shared/contracts'

/** Demo data for the GitHub Pages web preview (no Electron backend). */
export function createDemoSnapshot(): RuntimeSnapshot {
  const now = Date.now()
  return {
    creed: {
      name: 'DinoClaw',
      title: 'The Dino Creed',
      identity: 'A desktop AI buddy who stomps through real work with tiny arms and a big heart.',
      relationship: 'Your copilot — not a chatbot, not enterpriseware. Yours.',
      directives: [
        'Run on the user\'s machine first',
        'Ask before risky moves',
        'Remember what matters',
        'Keep the vibe human',
      ],
      vows: ['No cloud lock-in', 'No mystery charges', 'No terminal gatekeeping'],
      motto: 'AI for the people. Not the portfolio.',
      traits: [
        { name: 'Warmth', score: 88 },
        { name: 'Competence', score: 82 },
        { name: 'Chaos tolerance', score: 71 },
      ],
      mood: 'focused',
    },
    model: {
      provider: 'ollama',
      baseUrl: 'http://127.0.0.1:11434',
      model: 'llama3.2',
      apiKey: '',
      temperature: 0.2,
      maxTokens: 4096,
    },
    policy: {
      mode: 'review-risky',
      maxSteps: 12,
      allowedCommands: [],
      blockedPaths: [],
      requireApprovalAboveRisk: 'risky',
    },
    memory: [
      {
        id: 'mem-1',
        fact: 'Prefers plain language over jargon',
        category: 'preference',
        importance: 0.7,
        tags: ['preference'],
        createdAt: now - 86400000 * 3,
        accessCount: 2,
        lastAccessedAt: now - 3600000,
      },
      {
        id: 'mem-2',
        fact: 'Working on BostonAi.io projects',
        category: 'context',
        importance: 0.6,
        tags: ['work'],
        createdAt: now - 86400000,
        accessCount: 1,
        lastAccessedAt: now - 7200000,
      },
    ],
    runs: [
      {
        id: 'run-demo-1',
        goal: 'Organize Downloads folder',
        status: 'completed',
        startedAt: now - 3600000,
        finishedAt: now - 3500000,
        finalMessage: 'Sorted 42 files into folders. Desktop copilot mode — full power on the installed app.',
        steps: [],
        toolsUsed: ['list_directory', 'read_file'],
      },
    ],
    tools: [],
    skills: [],
    stats: {
      totalRuns: 12,
      successRate: 0.92,
      avgStepsPerRun: 4.2,
      toolUsage: { list_directory: 8, read_file: 6, execute_command: 3 },
      runsToday: 2,
      memoryCount: 2,
      uptime: 7200,
      topGoalPatterns: ['organize files', 'git status', 'summarize folder'],
    },
    auditLog: [],
    channels: {
      telegram: { botToken: '', allowedUsers: [], enabled: false },
      discord: { botToken: '', allowedUsers: [], enabled: false },
    },
    gateway: { running: false, port: 42617, host: '127.0.0.1', paired: false },
    docker: { enabled: false, available: false, image: 'alpine:3.20', network: 'none' },
    tunnel: { provider: 'none', running: false, url: '' },
    cronJobs: [],
    browser: { enabled: false, allowedDomains: [], requireApprovalForWrites: true },
    browserSession: { open: false, url: '', title: '', domain: '' },
    serviceStatus: 'not_installed',
    pluginActive: false,
    pluginStatus: null,
    queueDepth: 0,
    activeRunId: null,
    pendingApprovals: [],
    stomp: {
      config: {
        enabled: true,
        autonomy: 'notes_only',
        tickSeconds: 300,
        dailyNoteCap: 8,
        dailyActionCap: 3,
        minSpacingMs: 90 * 60 * 1000,
        idleFloorMs: 5 * 60 * 1000,
        quietHoursStart: 22,
        quietHoursEnd: 7,
        dismissStreakThreshold: 2,
        dismissCooldownMs: 6 * 60 * 60 * 1000,
        salienceThreshold: 0.55,
        topicCooldownMs: 12 * 60 * 60 * 1000,
        allowedPaths: [],
        watchPaths: [],
        watchEnabled: true,
      },
      journal: [
        {
          id: 'stomp-1',
          kind: 'note',
          title: 'Nest is looking tidy',
          body: 'This is a preview — install DinoClaw on your desktop for real stomps.',
          topic: 'preview',
          salience: 0.6,
          surfacedAt: now - 600000,
        },
      ],
      presence: 'holding',
      heldCount: 1,
      dismissStreak: 0,
      notesToday: 1,
      actionsToday: 0,
      phase: 'v0.4',
    },
  }
}
